import json, pygame
import math

def get_glyph(name):
    try:
        return get_svg_glyph(name)
    except KeyError:
        try:
            return get_json_glyph(name)
        except KeyError:
            raise KeyError('No glyph named "%s" exists in either `glyphs.svg` or `glyphs.json`.' % name)

def parse(coords): #TODO: make all of them the same size (roughly) WITHOUT USING pygame.transform.scale because we want to transform the list BEFORE turning it into a surface
    origin = (min([int(i[0]) for i in coords]), min([int(i[1]) for i in coords]))
    s = pygame.Surface((math.floor(max([int(i[0])-origin[0] for i in coords]))+10, math.floor(max([int(i[1])-origin[1] for i in coords]))+10))
    draw = [[int(i[0])-origin[0], int(i[1])-origin[1]] for i in coords]
    ndraw = draw.copy()
    ndraw.reverse()
    draw += ndraw
    pygame.draw.polygon(s, (255, 255, 255), [[i[0]+5, i[1]+5] for i in draw], 5)
    s.set_colorkey((0, 0, 0))
    return s

def get_json_glyph(name):
    with open('util/glyphs/glyphs/glyphs.json', 'r') as f:
        data = json.load(f)
        if name not in data.keys():
            raise KeyError('No glyph named "%s" exists.' % name)
    # parse data into coordinates
    out = [(0, 0)]
    rot = 0
    for i in data[name]:
        if i.startswith('.'):
            if i[1:].startswith('>'):
                rot = int(i[2:])
            elif i[1:].startswith('<'):
                rot = -int(i[2:])
            else:
                raise ValueError('Invalid rotation "%s".' % i)
        else:
            if i.startswith('>'):
                rot += int(i[1:])
            elif i.startswith('<'):
                rot -= int(i[1:])
            else:
                new_x = out[-1][0] + int(i) * math.cos(rot * math.pi / 180)
                new_y = out[-1][1] + int(i) * math.sin(rot * math.pi / 180)
                out.append((new_x, new_y))
    return parse(out)

def get_svg_glyph(name):
    with open('util/glyphs/glyphs/glyphs.svg', 'r') as f:
        isAdobe = 'Adobe Illustrator' in f.read() # it is included in a comment saying 'generated by Adobe Illustrator'
    if isAdobe:
        from xml.dom import minidom
        doc = minidom.parse('util/glyphs/glyphs/glyphs.svg')
        elms = doc.getElementsByTagName('g')
        for i in elms:
            if i.getAttribute('id') == name:
                out = i.getElementsByTagName('polyline')[0].getAttribute('points') # dunno what the attribute 'class' is...
                break
        # here we parse 'out'
        try:
            out = out.split(' ')
        except NameError:
            raise KeyError('No glyph named "%s" exists.' % name)
        out = [i.split(',') for i in out if i != '']
    else: pass #TODO: implement this. Unsure if this is even needed, but OH WELL
    return parse(out)
